config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  get "welcome/index"
  root "welcome#index"

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from rails blog",
      :to => "g54345@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	 extend FriendlyId  
  friendly_id :title, use: :slugged
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :quote_quoteauthors
  has_many :quoteauthors, through: :quote_quoteauthors
end

app/models/quote_quoteauthor.rb
class QuoteQuoteauthor < ActiveRecord::Base
  belongs_to :quote, dependent: :destroy
  belongs_to :quoteauthor
end

app/models/quoteauthor.rb
class Quoteauthor < ActiveRecord::Base
  has_many :quote_quoteauthors
  has_many :quotes, through: :quote_quoteauthors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    mailchimp.timeout = 10
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'pending'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_quote


  def get_quote
    @quote = Quote.order("RANDOM()").first
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new()
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request

		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Post successfully created."
		else
			render 'new', notice: "Something went wrong, post has not been created."
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post
		else
			render 'edit', notice: "Failed to update post."
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)  
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "project successfully created."
		else
			render 'new', notice: "Something went wrong, project has not been created."
		end
	end

	def show
	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project
		else
			render 'edit', notice: "Failed to update project."
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)  
	end

	def find_project
		@project = Project.friendly.find(params[:id])
	end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@posts = Post.all.order("created_at desc").limit(5)
		@projects = Project.all.order("created_at desc").limit(5)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>

		<%= f.label :name %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :message, "Write your message here" %><br>
		<%= f.text_area :message, as: :text %>

		<br>

<!-- 		<div class="hidden ">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div> -->

		<%= f.submit 'Send Message', class: "button" %>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SAS Blog</title>
	<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<!-- <a href="#" class="name">Thamó Csaba</a> -->
		<%= link_to 'Health & Nutrition', root_path, class: "name" %>
		<nav>
			<%= link_to "Posts", posts_path %>
			<%= link_to "Projects", projects_path %>
			<%= link_to "Newsletter", new_visitor_path %>
			<%= link_to "Contact", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>

		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
	</header>

<%= yield %>

	<footer id="main_footer">
		<p class="copyright">2016 Thamó Csaba</p>
		<p class="quote">"<%= @quote.content %>" / <%= @quote.quoteauthors.first.name %></p>
		<nav>
			<a href="http://github.com/csathaba" target="_blank"><i class="fa fa-github"></i></a>
		</nav>
	</footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@post, {only_path:false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = 'post.<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.title = '<%= @post.title %>';
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//csathaba-vitamins.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, "Write your article here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit %>

	<% if @post.id.present? %>
		<%= link_to 'Back', post_path(@post), class: "button" %>
	<% end %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Posts</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
		<div class="post">
			<!-- <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p> -->
			<h2><%= link_to post.title, post %></h2>
			<hr>
		</div>
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">Create a new Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<!-- <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p> -->
		<h1><%= @post.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @post.content %>
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to 'Edit', edit_post_path(@post) %>
			<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
		</div>
	<% end %>
	<hr>

	<div id="share_box">
		<p>Share The DO List</p>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

	<hr>

	<%= render 'disqus' %>

	<hr>

</div>

app/views/projects/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@project, {only_path:false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = 'project.<%= @project.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.title = '<%= @project.title %>';
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//csathabablog.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description, "Write your article here" %><br>
	<%= f.text_area :description %>

	<br>
	<br>

<!-- 	<%= f.label :link %><br>
	<%= f.text_field :link %>

	<br>
	<br> -->

	<%= f.submit %>

	<% if @project.id.present? %>
		<%= link_to 'Back', project_path(@project), class: "button" %>
	<% end %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
		<div class="post">
			<!-- <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p> -->
			<h2><%= link_to project.title, project %></h2>
			<hr>
		</div>
	<% end %>
</div>

<%= will_paginate @projects %>

app/views/projects/new.html.erb
<h1 id="page_title">Create a new Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<!-- <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p> -->
		<h1><%= @project.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @project.description %>

<!-- 		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank" > Visit <%= @project.title %> </a>
		</div> -->
		
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to 'Edit', edit_project_path(@project) %>
			<%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
		</div>
	<% end %>

	<hr>

	<div id="share_box">
		<p>Share The DO List</p>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@project, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@project, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

	<hr>

	<%= render 'disqus' %>

	<hr>

</div>

app/views/visitors/new.html.erb
<h1 id="page_title">Sign up for the Newsletter</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= simple_form_for @visitor do |f| %>
    <%= f.error_notification %>
    <%= f.input :email, label: false, :placeholder => 'Your email address...' %>
    <br/>
    <%= f.button :submit, "Sign up for the newsletter", :class => "submit" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>Welcome to the practical hands-on SAS blog, where you can learn the 80/20 of SAS data management and reporting.
			Focus on the things that are applicable, and practice on real-world projects and examples.</p>
	</div>
	<div class="col-2 homepage_content">
		<h2>Random posts</h2>
		<hr>
		<% @posts.each do |post| %>
			<h3><%= link_to post.title, post %></h3>
			<!-- <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p> -->
		<% end %>
	</div>
	<div class="col-3 homepage_content">
		<h2>Immersion Projects</h2>
		<hr>
		<% @projects.each do |project| %>
			<h3><%= link_to project.title, project %></h3>
			<!-- <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p> -->
		<% end %>
	</div>
</div>